import { useId, useMemo, useState, type FormEvent } from "react";
import { Info, Palette, Search, TriangleAlert } from "lucide-react";

import {
  fullSpectrumComponents,
  getFullSpectrumReferencePalette,
  type FullSpectrumReferenceColor,
  type FullSpectrumReferenceMode,
} from "../utils/cmyx-reference";
import { ColorSwatch } from "./ColorSwatch";

function colorMatchesQuery(color: FullSpectrumReferenceColor, query: string) {
  if (!query) return true;
  const searchable = [
    color.hex,
    ...color.recipes.flatMap((recipe) => [
      recipe.mode,
      recipe.label,
      ...recipe.components.flatMap((component) => [
        component.symbol,
        component.toolhead,
        component.name,
      ]),
    ]),
  ]
    .join(" ")
    .toLocaleLowerCase();
  return searchable.includes(query.toLocaleLowerCase());
}

export function CmyxReference() {
  const instanceId = useId().replace(/:/g, "");
  const [mode, setMode] = useState<FullSpectrumReferenceMode>("cmy");
  const [query, setQuery] = useState("");
  const palette = useMemo(() => getFullSpectrumReferencePalette(mode), [mode]);
  const visibleColors = useMemo(
    () => palette.filter((color) => colorMatchesQuery(color, query.trim())),
    [palette, query],
  );
  const components = fullSpectrumComponents[mode];

  const preventSearchNavigation = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
  };

  return (
    <section
      className="full-spectrum-reference"
      aria-labelledby={`${instanceId}-heading`}
    >
      <header className="full-spectrum-reference__header">
        <div className="full-spectrum-reference__title">
          <span className="full-spectrum-reference__icon" aria-hidden="true">
            <Palette />
          </span>
          <div>
            <h2 id={`${instanceId}-heading`}>Full Spectrum Color Reference</h2>
            <p>
              Browse every unique nominal color generated by the current 1/8
              Ratio grid, plus equal-weight Cycle recipes.
            </p>
          </div>
        </div>
        <dl className="full-spectrum-reference__counts" aria-label="Palette counts">
          <div>
            <dt>CMY</dt>
            <dd>{getFullSpectrumReferencePalette("cmy").length}</dd>
          </div>
          <div>
            <dt>CMYK</dt>
            <dd>{getFullSpectrumReferencePalette("cmyk").length}</dd>
          </div>
        </dl>
      </header>

      <div className="full-spectrum-reference__notice">
        <Info aria-hidden="true" />
        <p>
          Screen colors are nominal sRGB predictions, not measured print
          results. Geometry, layer height, translucency, spool lot, and process
          settings can change the physical color.
        </p>
      </div>

      <fieldset className="full-spectrum-reference__mode">
        <legend>Palette model</legend>
        <div>
          <label>
            <input
              type="radio"
              name={`${instanceId}-mode`}
              value="cmy"
              checked={mode === "cmy"}
              onChange={() => setMode("cmy")}
            />
            <span>
              <strong>CMY</strong>
              <small>Three components · 46 colors</small>
            </span>
          </label>
          <label>
            <input
              type="radio"
              name={`${instanceId}-mode`}
              value="cmyk"
              checked={mode === "cmyk"}
              onChange={() => setMode("cmyk")}
            />
            <span>
              <strong>CMYK Full Spectrum</strong>
              <small>Four components · 135 colors</small>
            </span>
          </label>
        </div>
      </fieldset>

      {mode === "cmyk" ? (
        <div className="full-spectrum-reference__warning">
          <TriangleAlert aria-hidden="true" />
          <p>
            CMYK is a theoretical reference. The built-in opaque Black remains
            solid-only; recipes containing K require a qualified and calibrated
            Full Spectrum black component.
          </p>
        </div>
      ) : null}

      <section
        className="full-spectrum-reference__loadout"
        aria-labelledby={`${instanceId}-loadout-heading`}
      >
        <div>
          <h3 id={`${instanceId}-loadout-heading`}>Reference loadout</h3>
          <p>The same nominal component colors used by the color engine.</p>
        </div>
        <ul>
          {components.map((component) => (
            <li key={component.symbol}>
              <ColorSwatch hex={component.hex} size="large" />
              <span>
                <strong>
                  {component.symbol} · {component.name}
                </strong>
                <small>
                  {component.toolhead} · {component.hex}
                </small>
              </span>
            </li>
          ))}
        </ul>
      </section>

      <form
        className="full-spectrum-reference__filters"
        role="search"
        onSubmit={preventSearchNavigation}
      >
        <label htmlFor={`${instanceId}-search`}>Search colors</label>
        <span>
          <Search aria-hidden="true" />
          <input
            id={`${instanceId}-search`}
            name="full-spectrum-color-search"
            type="search"
            value={query}
            placeholder="HEX, C/M/Y/K, toolhead, Ratio, or Cycle"
            onChange={(event) => setQuery(event.target.value)}
          />
        </span>
      </form>

      <div
        className="full-spectrum-reference__table-wrap"
        role="region"
        aria-label={`${mode.toUpperCase()} Full Spectrum color table`}
        tabIndex={0}
      >
        <table className="full-spectrum-reference__table">
          <caption aria-live="polite" aria-atomic="true">
            Showing {visibleColors.length} of {palette.length} unique {mode.toUpperCase()} colors.
          </caption>
          <thead>
            <tr>
              <th scope="col">Color</th>
              <th scope="col">HEX</th>
              <th scope="col">Method</th>
              <th scope="col">Recipe</th>
            </tr>
          </thead>
          <tbody>
            {visibleColors.length === 0 ? (
              <tr>
                <td className="full-spectrum-reference__empty" colSpan={4}>
                  No colors match this search. Clear the search or try a component
                  symbol such as C, M, Y, or K.
                </td>
              </tr>
            ) : (
              visibleColors.map((color) => {
                const primary = color.recipes[0];
                const equivalents = color.recipes.slice(1);
                return (
                  <tr key={color.hex}>
                    <td>
                      <ColorSwatch hex={color.hex} size="large" />
                      <span className="visually-hidden">Color {color.hex}</span>
                    </td>
                    <th scope="row">
                      <code>{color.hex}</code>
                    </th>
                    <td>
                      {[...new Set(color.recipes.map((recipe) => recipe.mode))].join(
                        " / ",
                      )}
                    </td>
                    <td>
                      <span className="full-spectrum-reference__recipe">
                        <strong>{primary.label}</strong>
                        {equivalents.map((recipe) => (
                          <small key={`${recipe.mode}-${recipe.label}`}>
                            Equivalent {recipe.mode}: {recipe.label}
                          </small>
                        ))}
                      </span>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
