//! Deterministic, bounded ZIP package writing for OPC/3MF containers.
//!
//! This module deliberately knows nothing about printers or slicer metadata. It
//! accepts generated byte buffers and selected entries from existing ZIP files,
//! writes them in a deterministic order to a temporary file next to the intended
//! destination, and returns the staged package for structural validation. The
//! caller must explicitly publish a successfully validated package.

use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, Metadata};
use std::io::{self, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};
use tempfile::{Builder as TempBuilder, NamedTempFile, PersistError, TempDir};
use thiserror::Error;
use zip::write::SimpleFileOptions;
use zip::{CompressionMethod, DateTime, ZipArchive, ZipWriter};

use crate::zip_preflight::advertised_zip_entry_count;
use crate::{OutputValidationReport, StagedOutputValidationError, StructuralOutputValidator};

const DETERMINISTIC_DEFLATE_LEVEL: i64 = 6;
const DETERMINISTIC_FILE_MODE: u32 = 0o644;

/// Resource limits enforced before and while a package is staged.
#[derive(Clone, Debug, PartialEq)]
pub struct OpcWriteLimits {
    /// Maximum number of entries in the output and in each source archive.
    pub max_entries: usize,
    /// Maximum UTF-8 byte length of a portable package path.
    pub max_entry_name_bytes: usize,
    /// Maximum uncompressed size of one generic generated or copied entry.
    pub max_entry_uncompressed_bytes: u64,
    /// Maximum uncompressed size of one `3D/*.model` entry.
    pub max_model_entry_uncompressed_bytes: u64,
    /// Maximum uncompressed size of one slicer `.config` entry.
    pub max_config_entry_uncompressed_bytes: u64,
    /// Maximum uncompressed size of one OPC `.rels` entry.
    pub max_relationship_entry_uncompressed_bytes: u64,
    /// Maximum total uncompressed size of all output entries.
    pub max_total_uncompressed_bytes: u64,
    /// Maximum byte size of one compressed source archive before snapshotting.
    pub max_source_archive_bytes: u64,
    /// Maximum advertised uncompressed/compressed ratio for copied entries.
    pub max_source_compression_ratio: f64,
    /// Buffer used to stream copied entries. It never grows with entry size.
    pub copy_buffer_bytes: usize,
}

impl Default for OpcWriteLimits {
    fn default() -> Self {
        Self {
            max_entries: 4_096,
            max_entry_name_bytes: 1_024,
            max_entry_uncompressed_bytes: 512 * 1024 * 1024,
            // The reference U1 project contains a monolithic model of about
            // 590 MiB, so a 1 GiB model limit is intentional. Metadata retains
            // substantially stricter limits.
            max_model_entry_uncompressed_bytes: 1024 * 1024 * 1024,
            max_config_entry_uncompressed_bytes: 64 * 1024 * 1024,
            max_relationship_entry_uncompressed_bytes: 8 * 1024 * 1024,
            max_total_uncompressed_bytes: 4 * 1024 * 1024 * 1024,
            max_source_archive_bytes: 4 * 1024 * 1024 * 1024,
            max_source_compression_ratio: 200.0,
            copy_buffer_bytes: 128 * 1024,
        }
    }
}

impl OpcWriteLimits {
    fn validate(&self) -> Result<(), OpcWriteError> {
        if self.max_entries == 0
            || self.max_entry_name_bytes == 0
            || self.max_entry_uncompressed_bytes == 0
            || self.max_model_entry_uncompressed_bytes == 0
            || self.max_config_entry_uncompressed_bytes == 0
            || self.max_relationship_entry_uncompressed_bytes == 0
            || self.max_total_uncompressed_bytes == 0
            || self.max_source_archive_bytes == 0
            || self.copy_buffer_bytes == 0
            || self.copy_buffer_bytes > 8 * 1024 * 1024
            || !self.max_source_compression_ratio.is_finite()
            || self.max_source_compression_ratio < 1.0
        {
            return Err(OpcWriteError::InvalidLimits(
                "all limits must be positive, the copy buffer must not exceed 8 MiB, and the compression ratio must be finite and at least 1"
                    .into(),
            ));
        }
        Ok(())
    }
}

/// Immutable identity recorded by analysis and required for every copied
/// source archive. Staging hashes a private bounded snapshot before reading ZIP
/// entries, so transient or permanent source changes cannot affect the output.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExpectedSourceIdentity {
    byte_size: u64,
    sha256: String,
}

impl ExpectedSourceIdentity {
    pub fn new(byte_size: u64, sha256: impl Into<String>) -> Result<Self, OpcWriteError> {
        let sha256 = sha256.into().to_ascii_lowercase();
        if sha256.len() != 64 || !sha256.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            return Err(OpcWriteError::InvalidExpectedSourceIdentity(
                "SHA-256 must contain exactly 64 hexadecimal characters".into(),
            ));
        }
        Ok(Self { byte_size, sha256 })
    }

    pub fn byte_size(&self) -> u64 {
        self.byte_size
    }

    pub fn sha256(&self) -> &str {
        &self.sha256
    }
}

/// The origin of an entry in a deterministic write report.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OpcEntryOrigin {
    Generated,
    Copied {
        source_archive: PathBuf,
        source_entry: String,
        raw: bool,
    },
}

/// One entry in the write report. Reports are sorted by `path`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OpcEntryWriteReport {
    pub path: String,
    pub origin: OpcEntryOrigin,
    pub uncompressed_bytes: u64,
}

/// An analyzed source identity that was reverified from the private staging
/// snapshot before any of its entries entered the output package.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub struct VerifiedSourceIdentity {
    pub byte_size: u64,
    pub sha256: String,
}

/// Reproducibility and audit data for a staged or published package.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OpcWriteReport {
    pub destination: PathBuf,
    pub package_bytes: u64,
    pub package_sha256: String,
    pub total_uncompressed_bytes: u64,
    pub entries: Vec<OpcEntryWriteReport>,
    pub verified_sources: Vec<VerifiedSourceIdentity>,
}

/// A deterministic package description that can be staged more than once.
#[derive(Debug)]
pub struct OpcPackageWriter {
    limits: OpcWriteLimits,
    entries: BTreeMap<String, PendingEntry>,
    verified_archives: BTreeMap<PathBuf, ExpectedSourceIdentity>,
    generated_uncompressed_bytes: u64,
}

#[derive(Clone, Debug)]
enum PendingEntry {
    Generated(Vec<u8>),
    Copied {
        source_archive: PathBuf,
        expected_identity: ExpectedSourceIdentity,
        source_entry: String,
        mode: CopyMode,
    },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum CopyMode {
    Recompress,
    TrustedRaw,
}

impl Default for OpcPackageWriter {
    fn default() -> Self {
        Self::new()
    }
}

impl OpcPackageWriter {
    pub fn new() -> Self {
        Self {
            limits: OpcWriteLimits::default(),
            entries: BTreeMap::new(),
            verified_archives: BTreeMap::new(),
            generated_uncompressed_bytes: 0,
        }
    }

    pub fn with_limits(limits: OpcWriteLimits) -> Result<Self, OpcWriteError> {
        limits.validate()?;
        Ok(Self {
            limits,
            entries: BTreeMap::new(),
            verified_archives: BTreeMap::new(),
            generated_uncompressed_bytes: 0,
        })
    }

    pub fn limits(&self) -> &OpcWriteLimits {
        &self.limits
    }

    pub fn entry_count(&self) -> usize {
        self.entries.len()
    }

    /// Registers an analyzed ZIP source whose immutable identity must be
    /// reverified during staging even when every output entry derived from it
    /// had to be rewritten. This keeps package manifests bound to the original
    /// 3MF rather than only to an intermediate rewrite archive.
    pub fn verify_zip_source(
        &mut self,
        source_archive: impl Into<PathBuf>,
        expected_identity: ExpectedSourceIdentity,
    ) -> Result<&mut Self, OpcWriteError> {
        let source_archive = source_archive.into();
        if let Some(existing) = self.verified_archives.get(&source_archive)
            && existing != &expected_identity
        {
            return Err(OpcWriteError::ConflictingExpectedSourceIdentity {
                path: source_archive,
            });
        }
        self.verified_archives
            .insert(source_archive, expected_identity);
        Ok(self)
    }

    /// Adds generated content. The buffer is kept until staging so the same
    /// package description can be staged again for a reproducibility check.
    pub fn add_bytes(
        &mut self,
        output_path: impl Into<String>,
        bytes: impl Into<Vec<u8>>,
    ) -> Result<&mut Self, OpcWriteError> {
        let output_path = output_path.into();
        validate_package_path(&output_path, false, &self.limits)?;
        let bytes = bytes.into();
        let byte_count = bytes.len() as u64;
        self.validate_entry_size(&output_path, byte_count)?;
        let generated_total = self
            .generated_uncompressed_bytes
            .checked_add(byte_count)
            .ok_or(OpcWriteError::PackageTooLarge {
                actual: u64::MAX,
                limit: self.limits.max_total_uncompressed_bytes,
            })?;
        if generated_total > self.limits.max_total_uncompressed_bytes {
            return Err(OpcWriteError::PackageTooLarge {
                actual: generated_total,
                limit: self.limits.max_total_uncompressed_bytes,
            });
        }
        self.insert_entry(output_path, PendingEntry::Generated(bytes))?;
        self.generated_uncompressed_bytes = generated_total;
        Ok(self)
    }

    /// Adds a source ZIP entry without loading its uncompressed contents into
    /// memory. The entry is decompressed and recompressed through a bounded
    /// buffer during staging.
    pub fn copy_zip_entry(
        &mut self,
        output_path: impl Into<String>,
        source_archive: impl Into<PathBuf>,
        expected_identity: ExpectedSourceIdentity,
        source_entry: impl Into<String>,
    ) -> Result<&mut Self, OpcWriteError> {
        let output_path = output_path.into();
        let source_entry = source_entry.into();
        validate_package_path(&output_path, false, &self.limits)?;
        validate_package_path(&source_entry, false, &self.limits)?;
        self.insert_entry(
            output_path,
            PendingEntry::Copied {
                source_archive: source_archive.into(),
                expected_identity,
                source_entry,
                mode: CopyMode::Recompress,
            },
        )?;
        Ok(self)
    }

    /// Adds an already validated source entry by copying its compressed payload
    /// verbatim. This is intended for unchanged, potentially very large geometry
    /// parts after the source package has passed the analyzer.
    ///
    /// Raw copy accepts the source ZIP's CRC and compressed size on trust. The
    /// package path is preserved so the ZIP library can normalize the timestamp
    /// and permissions without recompressing or retaining source timestamps.
    pub fn copy_zip_entry_raw(
        &mut self,
        source_archive: impl Into<PathBuf>,
        expected_identity: ExpectedSourceIdentity,
        source_entry: impl Into<String>,
    ) -> Result<&mut Self, OpcWriteError> {
        let source_entry = source_entry.into();
        validate_package_path(&source_entry, false, &self.limits)?;
        self.insert_entry(
            source_entry.clone(),
            PendingEntry::Copied {
                source_archive: source_archive.into(),
                expected_identity,
                source_entry,
                mode: CopyMode::TrustedRaw,
            },
        )?;
        Ok(self)
    }

    /// Writes a synchronized temporary package in the destination directory.
    ///
    /// No destination file is created or replaced here. The returned temporary
    /// path may be passed to the structural validator before `publish` is called.
    pub fn stage_to(&self, destination: impl AsRef<Path>) -> Result<StagedPackage, OpcWriteError> {
        self.limits.validate()?;
        if self.entries.is_empty() {
            return Err(OpcWriteError::EmptyPackage);
        }
        if self.entries.len() > self.limits.max_entries {
            return Err(OpcWriteError::TooManyEntries {
                actual: self.entries.len(),
                limit: self.limits.max_entries,
            });
        }

        let destination = normalized_destination(destination.as_ref())?;
        let PreparedSources {
            mut archives,
            aliases,
            identities,
        } = self.prepare_sources(&destination)?;
        let (prepared_entries, total_uncompressed_bytes) =
            self.prepare_entries(&aliases, &archives)?;
        let mut verified_sources = archives
            .values()
            .map(|source| VerifiedSourceIdentity {
                byte_size: source.expected_identity.byte_size,
                sha256: source.expected_identity.sha256.clone(),
            })
            .collect::<Vec<_>>();
        verified_sources.sort();
        verified_sources.dedup();

        let destination_parent = destination.parent().ok_or_else(|| {
            OpcWriteError::InvalidDestination("destination has no parent directory".into())
        })?;
        let mut temporary = NamedTempFile::new_in(destination_parent)?;
        {
            let mut zip = ZipWriter::new(temporary.as_file_mut());
            let fixed_time =
                DateTime::from_date_and_time(1980, 1, 1, 0, 0, 0).expect("the ZIP epoch is valid");
            let mut copy_buffer = vec![0_u8; self.limits.copy_buffer_bytes];

            for entry in &prepared_entries {
                match &entry.source {
                    PreparedEntrySource::Generated(bytes) => {
                        zip.start_file(
                            &entry.path,
                            deterministic_options(fixed_time, entry.uncompressed_bytes),
                        )?;
                        zip.write_all(bytes)?;
                    }
                    PreparedEntrySource::Copied {
                        canonical_archive,
                        source_index,
                        mode,
                    } => {
                        let source = archives.get_mut(canonical_archive).ok_or_else(|| {
                            OpcWriteError::InternalInvariant(format!(
                                "prepared source archive {canonical_archive:?} disappeared"
                            ))
                        })?;
                        let mut source_entry = source.archive.by_index(*source_index)?;
                        match mode {
                            CopyMode::Recompress => {
                                zip.start_file(
                                    &entry.path,
                                    deterministic_options(fixed_time, entry.uncompressed_bytes),
                                )?;
                                copy_exact(
                                    &mut source_entry,
                                    &mut zip,
                                    entry.uncompressed_bytes,
                                    &mut copy_buffer,
                                    &entry.path,
                                )?;
                            }
                            CopyMode::TrustedRaw => zip.raw_copy_file_touch(
                                source_entry,
                                fixed_time,
                                Some(DETERMINISTIC_FILE_MODE),
                            )?,
                        }
                    }
                }
            }
            zip.finish()?;
        }
        // Re-hash both the original source handle and the exact private
        // snapshot handle used by ZipArchive. The first check detects an
        // in-place source rewrite that preserves its path and inode; the
        // second detects unexpected snapshot mutation during staging.
        for (canonical, source) in archives {
            let PreparedSourceArchive {
                archive,
                expected_identity,
                source_identity,
                mut original_file,
                ..
            } = source;
            verify_open_source_identity(&mut original_file, &canonical, &expected_identity)?;
            ensure_source_path_identity(&source_identity, &expected_identity)?;
            let mut snapshot_file = archive.into_inner();
            verify_open_source_identity(&mut snapshot_file, &canonical, &expected_identity)?;
        }
        temporary.as_file_mut().flush()?;
        temporary.as_file().sync_all()?;

        let (package_bytes, package_sha256) = hash_open_file(temporary.as_file_mut())?;
        let report = OpcWriteReport {
            destination: destination.clone(),
            package_bytes,
            package_sha256,
            total_uncompressed_bytes,
            entries: prepared_entries
                .into_iter()
                .map(|entry| OpcEntryWriteReport {
                    path: entry.path,
                    origin: entry.origin,
                    uncompressed_bytes: entry.uncompressed_bytes,
                })
                .collect(),
            verified_sources,
        };

        Ok(StagedPackage {
            temporary,
            destination,
            source_identities: identities,
            report,
        })
    }

    fn validate_entry_size(&self, path: &str, size: u64) -> Result<(), OpcWriteError> {
        let limit = entry_size_limit(path, &self.limits);
        if size > limit {
            return Err(OpcWriteError::EntryTooLarge {
                path: path.to_owned(),
                actual: size,
                limit,
            });
        }
        Ok(())
    }

    fn insert_entry(&mut self, path: String, entry: PendingEntry) -> Result<(), OpcWriteError> {
        if self.entries.contains_key(&path) {
            return Err(OpcWriteError::DuplicateOutputEntry(path));
        }
        for existing in self.entries.keys() {
            if existing.eq_ignore_ascii_case(&path) {
                return Err(OpcWriteError::EquivalentOutputEntry {
                    existing: existing.clone(),
                    candidate: path,
                });
            }
            if part_name_is_prefix_of(existing, &path) || part_name_is_prefix_of(&path, existing) {
                return Err(OpcWriteError::OutputPartNameDerivationConflict {
                    first: existing.clone(),
                    second: path,
                });
            }
        }
        if self.entries.len() == self.limits.max_entries {
            return Err(OpcWriteError::TooManyEntries {
                actual: self.entries.len() + 1,
                limit: self.limits.max_entries,
            });
        }
        self.entries.insert(path, entry);
        Ok(())
    }

    fn prepare_sources(&self, destination: &Path) -> Result<PreparedSources, OpcWriteError> {
        let mut requested_by_original: BTreeMap<PathBuf, RequestedSource> = self
            .verified_archives
            .iter()
            .map(|(path, expected_identity)| {
                (
                    path.clone(),
                    RequestedSource {
                        expected_identity: expected_identity.clone(),
                        entries: BTreeSet::new(),
                    },
                )
            })
            .collect();
        for entry in self.entries.values() {
            if let PendingEntry::Copied {
                source_archive,
                expected_identity,
                source_entry,
                ..
            } = entry
            {
                if let Some(request) = requested_by_original.get_mut(source_archive) {
                    if request.expected_identity != *expected_identity {
                        return Err(OpcWriteError::ConflictingExpectedSourceIdentity {
                            path: source_archive.clone(),
                        });
                    }
                    request.entries.insert(source_entry.clone());
                } else {
                    requested_by_original.insert(
                        source_archive.clone(),
                        RequestedSource {
                            expected_identity: expected_identity.clone(),
                            entries: BTreeSet::from([source_entry.clone()]),
                        },
                    );
                }
            }
        }

        let mut aliases = BTreeMap::new();
        let mut requests_by_canonical: BTreeMap<PathBuf, RequestedSource> = BTreeMap::new();
        for (original, request) in requested_by_original {
            let canonical =
                fs::canonicalize(&original).map_err(|source| OpcWriteError::SourceIo {
                    path: original.clone(),
                    source,
                })?;
            aliases.insert(original, canonical.clone());
            if let Some(canonical_request) = requests_by_canonical.get_mut(&canonical) {
                if canonical_request.expected_identity != request.expected_identity {
                    return Err(OpcWriteError::ConflictingExpectedSourceIdentity {
                        path: canonical,
                    });
                }
                canonical_request.entries.extend(request.entries);
            } else {
                requests_by_canonical.insert(canonical, request);
            }
        }

        let mut sources = BTreeMap::new();
        let mut identities = Vec::new();
        let snapshot_directory = destination.parent().ok_or_else(|| {
            OpcWriteError::InvalidDestination("destination has no parent directory".into())
        })?;
        for (canonical, request) in requests_by_canonical {
            let path_metadata =
                fs::metadata(&canonical).map_err(|source| OpcWriteError::SourceIo {
                    path: canonical.clone(),
                    source,
                })?;
            validate_source_file_metadata(
                &canonical,
                &path_metadata,
                &request.expected_identity,
                self.limits.max_source_archive_bytes,
            )?;
            let mut file = File::open(&canonical).map_err(|source| OpcWriteError::SourceIo {
                path: canonical.clone(),
                source,
            })?;
            let metadata = file.metadata().map_err(|source| OpcWriteError::SourceIo {
                path: canonical.clone(),
                source,
            })?;
            validate_source_file_metadata(
                &canonical,
                &metadata,
                &request.expected_identity,
                self.limits.max_source_archive_bytes,
            )?;
            let identity = SourceIdentity::new(canonical.clone(), &metadata);
            ensure_destination_is_not_source(destination, &identity)?;
            let snapshot = snapshot_source_archive(
                &mut file,
                &canonical,
                &request.expected_identity,
                self.limits.max_source_archive_bytes,
                snapshot_directory,
            )?;
            ensure_source_path_identity(&identity, &request.expected_identity)?;

            let mut archive_file = snapshot
                .reopen()
                .map_err(|source| OpcWriteError::SourceIo {
                    path: canonical.clone(),
                    source,
                })?;
            let advertised_entries =
                advertised_zip_entry_count(&mut archive_file).map_err(|reason| {
                    OpcWriteError::InvalidSourceCentralDirectory {
                        archive: canonical.clone(),
                        reason,
                    }
                })?;
            let max_entries = u64::try_from(self.limits.max_entries).unwrap_or(u64::MAX);
            if advertised_entries > max_entries {
                return Err(OpcWriteError::SourceArchiveTooManyEntries {
                    path: canonical,
                    actual: usize::try_from(advertised_entries).unwrap_or(usize::MAX),
                    limit: self.limits.max_entries,
                });
            }
            let mut archive =
                ZipArchive::new(archive_file).map_err(|source| OpcWriteError::SourceZip {
                    path: canonical.clone(),
                    source,
                })?;
            let central_directory_reader =
                snapshot
                    .reopen()
                    .map_err(|source| OpcWriteError::SourceIo {
                        path: canonical.clone(),
                        source,
                    })?;
            validate_source_central_directory(
                central_directory_reader,
                archive.central_directory_start(),
                &canonical,
                &self.limits,
            )?;
            if archive.len() > self.limits.max_entries {
                return Err(OpcWriteError::SourceArchiveTooManyEntries {
                    path: canonical,
                    actual: archive.len(),
                    limit: self.limits.max_entries,
                });
            }

            let mut seen = BTreeSet::new();
            let mut selected = BTreeMap::new();
            for index in 0..archive.len() {
                let entry = archive
                    .by_index(index)
                    .map_err(|source| OpcWriteError::SourceZip {
                        path: canonical.clone(),
                        source,
                    })?;
                let name = std::str::from_utf8(entry.name_raw())
                    .map_err(|_| OpcWriteError::NonUtf8SourceEntryName {
                        archive: canonical.clone(),
                    })?
                    .to_owned();
                validate_package_path(&name, entry.is_dir(), &self.limits)?;
                if !seen.insert(name.clone()) {
                    return Err(OpcWriteError::DuplicateSourceEntry {
                        archive: canonical.clone(),
                        entry: name,
                    });
                }
                if entry.encrypted() {
                    return Err(OpcWriteError::EncryptedSourceEntry {
                        archive: canonical.clone(),
                        entry: name,
                    });
                }
                if is_symbolic_link(entry.unix_mode()) {
                    return Err(OpcWriteError::SymbolicLinkSourceEntry {
                        archive: canonical.clone(),
                        entry: name,
                    });
                }
                if request.entries.contains(&name) {
                    if entry.is_dir() {
                        return Err(OpcWriteError::SourceEntryIsDirectory {
                            archive: canonical.clone(),
                            entry: name,
                        });
                    }
                    let ratio = compression_ratio(entry.size(), entry.compressed_size());
                    if ratio > self.limits.max_source_compression_ratio {
                        return Err(OpcWriteError::SourceCompressionRatioExceeded {
                            archive: canonical.clone(),
                            entry: name,
                            actual: ratio,
                            limit: self.limits.max_source_compression_ratio,
                        });
                    }
                    selected.insert(
                        name,
                        SelectedSourceEntry {
                            index,
                            uncompressed_bytes: entry.size(),
                        },
                    );
                }
            }
            for requested in request.entries {
                if !selected.contains_key(&requested) {
                    return Err(OpcWriteError::MissingSourceEntry {
                        archive: canonical.clone(),
                        entry: requested,
                    });
                }
            }

            identities.push(identity.clone());
            sources.insert(
                canonical,
                PreparedSourceArchive {
                    archive,
                    selected,
                    expected_identity: request.expected_identity,
                    source_identity: identity,
                    original_file: file,
                    _snapshot: snapshot,
                },
            );
        }
        Ok(PreparedSources {
            archives: sources,
            aliases,
            identities,
        })
    }

    fn prepare_entries<'a>(
        &'a self,
        source_aliases: &BTreeMap<PathBuf, PathBuf>,
        sources: &BTreeMap<PathBuf, PreparedSourceArchive>,
    ) -> Result<(Vec<PreparedEntry<'a>>, u64), OpcWriteError> {
        let mut total = 0_u64;
        let mut prepared = Vec::with_capacity(self.entries.len());
        for (path, source) in &self.entries {
            let (prepared_source, origin, uncompressed_bytes) = match source {
                PendingEntry::Generated(bytes) => (
                    PreparedEntrySource::Generated(bytes.as_slice()),
                    OpcEntryOrigin::Generated,
                    bytes.len() as u64,
                ),
                PendingEntry::Copied {
                    source_archive,
                    source_entry,
                    mode,
                    ..
                } => {
                    let canonical = source_aliases.get(source_archive).ok_or_else(|| {
                        OpcWriteError::InternalInvariant(format!(
                            "source alias {source_archive:?} was not prepared"
                        ))
                    })?;
                    let selected = sources
                        .get(canonical)
                        .and_then(|source| source.selected.get(source_entry))
                        .ok_or_else(|| {
                            OpcWriteError::InternalInvariant(format!(
                                "source entry {source_entry:?} was not prepared"
                            ))
                        })?;
                    self.validate_entry_size(path, selected.uncompressed_bytes)?;
                    (
                        PreparedEntrySource::Copied {
                            canonical_archive: canonical.clone(),
                            source_index: selected.index,
                            mode: *mode,
                        },
                        OpcEntryOrigin::Copied {
                            source_archive: source_archive.clone(),
                            source_entry: source_entry.clone(),
                            raw: *mode == CopyMode::TrustedRaw,
                        },
                        selected.uncompressed_bytes,
                    )
                }
            };
            total =
                total
                    .checked_add(uncompressed_bytes)
                    .ok_or(OpcWriteError::PackageTooLarge {
                        actual: u64::MAX,
                        limit: self.limits.max_total_uncompressed_bytes,
                    })?;
            if total > self.limits.max_total_uncompressed_bytes {
                return Err(OpcWriteError::PackageTooLarge {
                    actual: total,
                    limit: self.limits.max_total_uncompressed_bytes,
                });
            }
            prepared.push(PreparedEntry {
                path: path.clone(),
                source: prepared_source,
                origin,
                uncompressed_bytes,
            });
        }
        Ok((prepared, total))
    }
}

/// A synchronized temporary package awaiting validation and publication.
/// Dropping this value removes the temporary file and leaves the destination
/// untouched.
#[derive(Debug)]
pub struct StagedPackage {
    temporary: NamedTempFile,
    destination: PathBuf,
    source_identities: Vec<SourceIdentity>,
    report: OpcWriteReport,
}

impl StagedPackage {
    pub fn path(&self) -> &Path {
        self.temporary.path()
    }

    pub fn destination(&self) -> &Path {
        &self.destination
    }

    pub fn report(&self) -> &OpcWriteReport {
        &self.report
    }

    /// Runs the structural publication gate and returns the only public type
    /// that can publish this staged package.
    pub fn validate(self) -> Result<ValidatedStagedPackage, StagedPackageValidationError> {
        let destination_parent = self.destination.parent().ok_or_else(|| {
            OpcWriteError::InvalidDestination("destination has no parent directory".into())
        })?;
        let private_directory = private_staging_directory(destination_parent)?;
        let mut validation_snapshot = snapshot_staged_package(
            self.temporary.as_file(),
            &self.report,
            private_directory.path(),
        )?;
        let validator =
            StructuralOutputValidator::new(crate::OutputValidationPolicy::strict_unsliced());
        let validation_file = validation_snapshot
            .as_file()
            .try_clone()
            .map_err(|source| StagedOutputValidationError::Open {
                path: self.destination.clone(),
                source,
            })?;
        let validation = validator.validate_reader(validation_file);
        if !validation.is_valid || validation.has_errors() {
            return Err(StagedPackageValidationError::Blocked {
                report: Box::new(validation),
            });
        }
        verify_staged_package_identity(&mut validation_snapshot, &self.report)?;
        Ok(ValidatedStagedPackage {
            private_directory,
            temporary: validation_snapshot,
            destination: self.destination,
            source_identities: self.source_identities,
            report: self.report,
            validation,
        })
    }
}

/// A staged package that passed structural validation and may be published.
#[derive(Debug)]
pub struct ValidatedStagedPackage {
    // Keep the directory alive until publication. Its path is never exposed by
    // this capability, and Unix builds create it with mode 0700.
    private_directory: TempDir,
    temporary: NamedTempFile,
    destination: PathBuf,
    source_identities: Vec<SourceIdentity>,
    report: OpcWriteReport,
    validation: OutputValidationReport,
}

impl ValidatedStagedPackage {
    pub fn destination(&self) -> &Path {
        &self.destination
    }

    pub fn report(&self) -> &OpcWriteReport {
        &self.report
    }

    pub fn validation_report(&self) -> &OutputValidationReport {
        &self.validation
    }

    /// Atomically publishes a package that has passed the structural gate.
    /// Publication never overwrites an existing destination. A future replace
    /// workflow must bind explicit user consent to the destination identity.
    pub fn publish(mut self) -> Result<OpcWriteReport, OpcWriteError> {
        ensure_open_file_matches_path(self.temporary.as_file(), self.temporary.path())?;
        verify_staged_package_identity(&mut self.temporary, &self.report)?;
        // Check again after hashing so a path replacement cannot hide inside a
        // long digest pass. The source name is protected from other OS users by
        // the private staging directory retained by this capability.
        ensure_open_file_matches_path(self.temporary.as_file(), self.temporary.path())?;
        for source in &self.source_identities {
            ensure_destination_is_not_source(&self.destination, source)?;
        }

        let destination = self.destination.clone();
        if destination
            .try_exists()
            .map_err(|source| OpcWriteError::Publish {
                path: destination.clone(),
                source,
            })?
        {
            return Err(OpcWriteError::OutputExists(destination));
        }
        self.temporary
            .persist_noclobber(&destination)
            .map_err(|error| map_persist_error(&destination, error))?;
        sync_parent_directory(&destination)?;
        // The persisted file left the private directory. Explicitly retain the
        // guard until after rename and directory synchronization.
        drop(self.private_directory);
        Ok(self.report)
    }
}

#[derive(Debug, Error)]
pub enum StagedPackageValidationError {
    #[error(transparent)]
    Prepare(#[from] OpcWriteError),
    #[error(transparent)]
    Validate(#[from] StagedOutputValidationError),
    #[error("staged 3MF package failed structural validation")]
    Blocked { report: Box<OutputValidationReport> },
}

impl StagedPackageValidationError {
    pub fn report(&self) -> Option<&OutputValidationReport> {
        match self {
            Self::Prepare(_) | Self::Validate(_) => None,
            Self::Blocked { report } => Some(report),
        }
    }
}

struct PreparedSourceArchive {
    archive: ZipArchive<File>,
    selected: BTreeMap<String, SelectedSourceEntry>,
    expected_identity: ExpectedSourceIdentity,
    source_identity: SourceIdentity,
    original_file: File,
    _snapshot: NamedTempFile,
}

struct PreparedSources {
    archives: BTreeMap<PathBuf, PreparedSourceArchive>,
    aliases: BTreeMap<PathBuf, PathBuf>,
    identities: Vec<SourceIdentity>,
}

#[derive(Clone, Debug)]
struct RequestedSource {
    expected_identity: ExpectedSourceIdentity,
    entries: BTreeSet<String>,
}

#[derive(Clone, Debug)]
struct SelectedSourceEntry {
    index: usize,
    uncompressed_bytes: u64,
}

struct PreparedEntry<'a> {
    path: String,
    source: PreparedEntrySource<'a>,
    origin: OpcEntryOrigin,
    uncompressed_bytes: u64,
}

enum PreparedEntrySource<'a> {
    Generated(&'a [u8]),
    Copied {
        canonical_archive: PathBuf,
        source_index: usize,
        mode: CopyMode,
    },
}

#[derive(Clone, Debug)]
struct SourceIdentity {
    canonical_path: PathBuf,
    #[cfg(unix)]
    device: u64,
    #[cfg(unix)]
    inode: u64,
}

impl SourceIdentity {
    fn new(canonical_path: PathBuf, metadata: &Metadata) -> Self {
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            Self {
                canonical_path,
                device: metadata.dev(),
                inode: metadata.ino(),
            }
        }
        #[cfg(not(unix))]
        {
            let _ = metadata;
            Self { canonical_path }
        }
    }

    fn matches_metadata(&self, metadata: &Metadata) -> bool {
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            self.device == metadata.dev() && self.inode == metadata.ino()
        }
        #[cfg(not(unix))]
        {
            let _ = metadata;
            false
        }
    }
}

#[derive(Debug, Error)]
pub enum OpcWriteError {
    #[error("invalid OPC writer limits: {0}")]
    InvalidLimits(String),
    #[error("invalid expected source identity: {0}")]
    InvalidExpectedSourceIdentity(String),
    #[error("conflicting expected identities were supplied for source archive {path:?}")]
    ConflictingExpectedSourceIdentity { path: PathBuf },
    #[error(
        "source archive {path:?} changed after analysis: expected {expected_bytes} bytes/{expected_sha256}, found {actual_bytes} bytes/{actual_sha256}"
    )]
    SourceIdentityMismatch {
        path: PathBuf,
        expected_bytes: u64,
        actual_bytes: u64,
        expected_sha256: String,
        actual_sha256: String,
    },
    #[error(
        "source archive {path:?} changed size after analysis: expected {expected_bytes} bytes, found {actual_bytes} bytes"
    )]
    SourceSizeMismatch {
        path: PathBuf,
        expected_bytes: u64,
        actual_bytes: u64,
    },
    #[error("source archive path changed during staging: {0:?}")]
    SourcePathIdentityChanged(PathBuf),
    #[error("package contains no entries")]
    EmptyPackage,
    #[error(
        "staged package changed after validation: expected {expected_bytes} bytes/{expected_sha256}, found {actual_bytes} bytes/{actual_sha256}"
    )]
    StagedPackageIdentityMismatch {
        expected_bytes: u64,
        actual_bytes: u64,
        expected_sha256: String,
        actual_sha256: String,
    },
    #[error("staged package path no longer identifies the synchronized temporary file")]
    StagedPackagePathIdentityChanged,
    #[error("unsafe package entry path {path:?}: {reason}")]
    UnsafeEntryPath { path: String, reason: String },
    #[error("duplicate output entry {0:?}")]
    DuplicateOutputEntry(String),
    #[error("output entry {candidate:?} is case-equivalent to existing OPC part {existing:?}")]
    EquivalentOutputEntry { existing: String, candidate: String },
    #[error("OPC part names {first:?} and {second:?} have a forbidden prefix derivation")]
    OutputPartNameDerivationConflict { first: String, second: String },
    #[error("package contains {actual} entries; limit is {limit}")]
    TooManyEntries { actual: usize, limit: usize },
    #[error("entry {path:?} expands to {actual} bytes; limit is {limit}")]
    EntryTooLarge {
        path: String,
        actual: u64,
        limit: u64,
    },
    #[error("package expands to {actual} bytes; limit is {limit}")]
    PackageTooLarge { actual: u64, limit: u64 },
    #[error("invalid destination: {0}")]
    InvalidDestination(String),
    #[error("source archive {path:?} could not be accessed: {source}")]
    SourceIo {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("source archive must be a regular file: {0:?}")]
    SourceNotRegularFile(PathBuf),
    #[error("source archive {path:?} is {actual} bytes; limit is {limit} bytes")]
    SourceArchiveTooLarge {
        path: PathBuf,
        actual: u64,
        limit: u64,
    },
    #[error("source archive {path:?} is not a valid ZIP: {source}")]
    SourceZip {
        path: PathBuf,
        #[source]
        source: zip::result::ZipError,
    },
    #[error("source archive {archive:?} has an invalid central directory: {reason}")]
    InvalidSourceCentralDirectory { archive: PathBuf, reason: String },
    #[error("source archive {path:?} contains {actual} entries; limit is {limit}")]
    SourceArchiveTooManyEntries {
        path: PathBuf,
        actual: usize,
        limit: usize,
    },
    #[error("source archive {archive:?} contains a non-UTF-8 entry name")]
    NonUtf8SourceEntryName { archive: PathBuf },
    #[error("source archive {archive:?} contains duplicate entry {entry:?}")]
    DuplicateSourceEntry { archive: PathBuf, entry: String },
    #[error(
        "source archive {archive:?} contains case-equivalent OPC parts {existing:?} and {candidate:?}"
    )]
    EquivalentSourceEntry {
        archive: PathBuf,
        existing: String,
        candidate: String,
    },
    #[error(
        "source archive {archive:?} contains prefix-derived OPC parts {first:?} and {second:?}"
    )]
    SourcePartNameDerivationConflict {
        archive: PathBuf,
        first: String,
        second: String,
    },
    #[error("encrypted source entry is not supported: {archive:?}:{entry}")]
    EncryptedSourceEntry { archive: PathBuf, entry: String },
    #[error("symbolic-link source entry is not supported: {archive:?}:{entry}")]
    SymbolicLinkSourceEntry { archive: PathBuf, entry: String },
    #[error("source entry does not exist: {archive:?}:{entry}")]
    MissingSourceEntry { archive: PathBuf, entry: String },
    #[error("source entry is a directory: {archive:?}:{entry}")]
    SourceEntryIsDirectory { archive: PathBuf, entry: String },
    #[error(
        "source entry {archive:?}:{entry} has compression ratio {actual:.2}; limit is {limit:.2}"
    )]
    SourceCompressionRatioExceeded {
        archive: PathBuf,
        entry: String,
        actual: f64,
        limit: f64,
    },
    #[error("destination {destination:?} resolves to source archive {source_archive:?}")]
    SourceDestinationCollision {
        destination: PathBuf,
        source_archive: PathBuf,
    },
    #[error("destination already exists: {0:?}")]
    OutputExists(PathBuf),
    #[error("failed to publish package at {path:?}: {source}")]
    Publish {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error(
        "published package at {path:?}, but its parent directory could not be synchronized: {source}"
    )]
    DirectorySync {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("copied entry {path:?} ended after {actual} bytes; expected {expected}")]
    CopiedEntrySizeMismatch {
        path: String,
        actual: u64,
        expected: u64,
    },
    #[error("internal OPC writer invariant failed: {0}")]
    InternalInvariant(String),
    #[error(transparent)]
    Io(#[from] io::Error),
    #[error(transparent)]
    Zip(#[from] zip::result::ZipError),
}

fn validate_package_path(
    path: &str,
    is_directory: bool,
    limits: &OpcWriteLimits,
) -> Result<(), OpcWriteError> {
    let unsafe_path = |reason: &str| OpcWriteError::UnsafeEntryPath {
        path: path.to_owned(),
        reason: reason.to_owned(),
    };
    if path.is_empty() {
        return Err(unsafe_path("empty path"));
    }
    if path.len() > limits.max_entry_name_bytes {
        return Err(unsafe_path("path exceeds the configured byte limit"));
    }
    if path.starts_with('/') || path.starts_with('\\') {
        return Err(unsafe_path("absolute path"));
    }
    if path.contains('\\') {
        return Err(unsafe_path("backslash path separator"));
    }
    if path.contains('\0')
        || path.contains('?')
        || path.contains('#')
        || path.contains('%')
        || path.chars().any(char::is_control)
    {
        return Err(unsafe_path(
            "control character, query, fragment, or percent escape",
        ));
    }
    if !is_directory && path.ends_with('/') {
        return Err(unsafe_path("directory entry is not valid output content"));
    }

    let segments: Vec<_> = path.split('/').collect();
    for (index, segment) in segments.iter().enumerate() {
        if segment.is_empty() && !(is_directory && index + 1 == segments.len()) {
            return Err(unsafe_path("empty path segment"));
        }
        if matches!(*segment, "." | "..") {
            return Err(unsafe_path("dot traversal segment"));
        }
        if segment.contains(':') {
            return Err(unsafe_path(
                "colon is not allowed in a portable package path",
            ));
        }
    }
    Ok(())
}

fn part_name_is_prefix_of(candidate_prefix: &str, candidate_child: &str) -> bool {
    let prefix = candidate_prefix.to_ascii_lowercase();
    let child = candidate_child.to_ascii_lowercase();
    child
        .strip_prefix(&prefix)
        .is_some_and(|remainder| remainder.starts_with('/'))
}

fn validate_source_central_directory(
    mut reader: File,
    central_directory_start: u64,
    archive: &Path,
    limits: &OpcWriteLimits,
) -> Result<(), OpcWriteError> {
    const CENTRAL_FILE_HEADER: [u8; 4] = [0x50, 0x4b, 0x01, 0x02];
    const CENTRAL_DIRECTORY_TERMINATORS: [[u8; 4]; 4] = [
        [0x50, 0x4b, 0x05, 0x05], // central-directory digital signature
        [0x50, 0x4b, 0x06, 0x06], // ZIP64 end of central directory
        [0x50, 0x4b, 0x06, 0x07], // ZIP64 end locator
        [0x50, 0x4b, 0x05, 0x06], // end of central directory
    ];

    reader
        .seek(SeekFrom::Start(central_directory_start))
        .map_err(|source| OpcWriteError::SourceIo {
            path: archive.to_owned(),
            source,
        })?;
    let mut names = BTreeSet::new();
    let mut part_names = BTreeMap::<String, String>::new();
    let mut count = 0_usize;
    loop {
        let mut signature = [0_u8; 4];
        reader.read_exact(&mut signature).map_err(|source| {
            OpcWriteError::InvalidSourceCentralDirectory {
                archive: archive.to_owned(),
                reason: format!("failed to read a central-directory signature: {source}"),
            }
        })?;
        if signature != CENTRAL_FILE_HEADER {
            if CENTRAL_DIRECTORY_TERMINATORS.contains(&signature) {
                break;
            }
            return Err(OpcWriteError::InvalidSourceCentralDirectory {
                archive: archive.to_owned(),
                reason: format!("unexpected record signature {signature:02x?}"),
            });
        }

        // The fixed portion after the four-byte signature is 42 bytes. Name,
        // extra-field, and comment lengths are little-endian u16 fields at
        // offsets 24, 26, and 28 within this remainder.
        let mut fixed = [0_u8; 42];
        reader.read_exact(&mut fixed).map_err(|source| {
            OpcWriteError::InvalidSourceCentralDirectory {
                archive: archive.to_owned(),
                reason: format!("truncated central file header: {source}"),
            }
        })?;
        let name_len = usize::from(u16::from_le_bytes([fixed[24], fixed[25]]));
        let extra_len = u64::from(u16::from_le_bytes([fixed[26], fixed[27]]));
        let comment_len = u64::from(u16::from_le_bytes([fixed[28], fixed[29]]));
        if name_len > limits.max_entry_name_bytes {
            return Err(OpcWriteError::InvalidSourceCentralDirectory {
                archive: archive.to_owned(),
                reason: format!(
                    "entry name has {name_len} bytes; limit is {}",
                    limits.max_entry_name_bytes
                ),
            });
        }
        let mut raw_name = vec![0_u8; name_len];
        reader.read_exact(&mut raw_name).map_err(|source| {
            OpcWriteError::InvalidSourceCentralDirectory {
                archive: archive.to_owned(),
                reason: format!("truncated central entry name: {source}"),
            }
        })?;
        let name = std::str::from_utf8(&raw_name)
            .map_err(|_| OpcWriteError::NonUtf8SourceEntryName {
                archive: archive.to_owned(),
            })?
            .to_owned();
        validate_package_path(&name, name.ends_with('/'), limits)?;
        if !names.insert(name.clone()) {
            return Err(OpcWriteError::DuplicateSourceEntry {
                archive: archive.to_owned(),
                entry: name,
            });
        }
        if !name.ends_with('/') {
            let comparison_name = name.to_ascii_lowercase();
            if let Some(existing) = part_names.get(&comparison_name) {
                return Err(OpcWriteError::EquivalentSourceEntry {
                    archive: archive.to_owned(),
                    existing: existing.clone(),
                    candidate: name,
                });
            }
            if let Some(existing) = part_names
                .values()
                .find(|existing| {
                    part_name_is_prefix_of(existing, &name)
                        || part_name_is_prefix_of(&name, existing)
                })
                .cloned()
            {
                return Err(OpcWriteError::SourcePartNameDerivationConflict {
                    archive: archive.to_owned(),
                    first: existing,
                    second: name,
                });
            }
            part_names.insert(comparison_name, name);
        }
        count += 1;
        if count > limits.max_entries {
            return Err(OpcWriteError::SourceArchiveTooManyEntries {
                path: archive.to_owned(),
                actual: count,
                limit: limits.max_entries,
            });
        }
        let skip = extra_len.checked_add(comment_len).ok_or_else(|| {
            OpcWriteError::InvalidSourceCentralDirectory {
                archive: archive.to_owned(),
                reason: "central entry metadata length overflow".into(),
            }
        })?;
        reader
            .seek(SeekFrom::Current(
                i64::try_from(skip).expect("two u16 values fit i64"),
            ))
            .map_err(|source| OpcWriteError::SourceIo {
                path: archive.to_owned(),
                source,
            })?;
    }
    Ok(())
}

fn normalized_destination(destination: &Path) -> Result<PathBuf, OpcWriteError> {
    let file_name = destination
        .file_name()
        .ok_or_else(|| OpcWriteError::InvalidDestination("destination must name a file".into()))?;
    if file_name.is_empty() {
        return Err(OpcWriteError::InvalidDestination(
            "destination must name a file".into(),
        ));
    }
    let parent = destination
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let canonical_parent = fs::canonicalize(parent).map_err(|source| {
        OpcWriteError::InvalidDestination(format!(
            "destination directory {parent:?} cannot be resolved: {source}"
        ))
    })?;
    if !canonical_parent.is_dir() {
        return Err(OpcWriteError::InvalidDestination(format!(
            "destination parent {canonical_parent:?} is not a directory"
        )));
    }
    Ok(canonical_parent.join(file_name))
}

fn private_staging_directory(parent: &Path) -> Result<TempDir, OpcWriteError> {
    let mut builder = TempBuilder::new();
    builder.prefix(".u1-validated-");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        builder.permissions(fs::Permissions::from_mode(0o700));
    }
    Ok(builder.tempdir_in(parent)?)
}

fn snapshot_staged_package(
    source: &File,
    report: &OpcWriteReport,
    private_directory: &Path,
) -> Result<NamedTempFile, OpcWriteError> {
    let mut source = source.try_clone()?;
    source.seek(SeekFrom::Start(0))?;
    let mut snapshot = NamedTempFile::new_in(private_directory)?;
    let mut buffer = [0_u8; 128 * 1024];
    let mut bytes = 0_u64;
    let mut hasher = Sha256::new();
    let read_limit = report.package_bytes.saturating_add(1);
    while bytes < read_limit {
        let remaining = read_limit - bytes;
        let requested = usize::try_from(remaining.min(buffer.len() as u64))
            .expect("bounded buffer length fits usize");
        let count = source.read(&mut buffer[..requested])?;
        if count == 0 {
            break;
        }
        snapshot.write_all(&buffer[..count])?;
        hasher.update(&buffer[..count]);
        bytes += count as u64;
    }
    let sha256 = hex::encode(hasher.finalize());
    if bytes != report.package_bytes || sha256 != report.package_sha256 {
        return Err(OpcWriteError::StagedPackageIdentityMismatch {
            expected_bytes: report.package_bytes,
            actual_bytes: bytes,
            expected_sha256: report.package_sha256.clone(),
            actual_sha256: sha256,
        });
    }
    snapshot.as_file_mut().flush()?;
    snapshot.as_file().sync_all()?;
    Ok(snapshot)
}

fn verify_staged_package_identity(
    package: &mut NamedTempFile,
    report: &OpcWriteReport,
) -> Result<(), OpcWriteError> {
    let (actual_bytes, actual_sha256) = hash_open_file_at_most(
        package.as_file_mut(),
        report.package_bytes.saturating_add(1),
    )?;
    if actual_bytes != report.package_bytes || actual_sha256 != report.package_sha256 {
        return Err(OpcWriteError::StagedPackageIdentityMismatch {
            expected_bytes: report.package_bytes,
            actual_bytes,
            expected_sha256: report.package_sha256.clone(),
            actual_sha256,
        });
    }
    Ok(())
}

fn validate_source_file_metadata(
    path: &Path,
    metadata: &Metadata,
    expected: &ExpectedSourceIdentity,
    max_source_archive_bytes: u64,
) -> Result<(), OpcWriteError> {
    if !metadata.file_type().is_file() {
        return Err(OpcWriteError::SourceNotRegularFile(path.to_owned()));
    }
    let actual_bytes = metadata.len();
    if actual_bytes > max_source_archive_bytes {
        return Err(OpcWriteError::SourceArchiveTooLarge {
            path: path.to_owned(),
            actual: actual_bytes,
            limit: max_source_archive_bytes,
        });
    }
    if actual_bytes != expected.byte_size {
        return Err(OpcWriteError::SourceSizeMismatch {
            path: path.to_owned(),
            expected_bytes: expected.byte_size,
            actual_bytes,
        });
    }
    Ok(())
}

fn snapshot_source_archive(
    source: &mut File,
    source_path: &Path,
    expected: &ExpectedSourceIdentity,
    max_source_archive_bytes: u64,
    snapshot_directory: &Path,
) -> Result<NamedTempFile, OpcWriteError> {
    source.seek(SeekFrom::Start(0))?;
    let mut snapshot = NamedTempFile::new_in(snapshot_directory)?;
    let mut buffer = [0_u8; 128 * 1024];
    let mut actual_bytes = 0_u64;
    let mut hasher = Sha256::new();
    loop {
        let count = source.read(&mut buffer)?;
        if count == 0 {
            break;
        }
        actual_bytes =
            actual_bytes
                .checked_add(count as u64)
                .ok_or(OpcWriteError::SourceArchiveTooLarge {
                    path: source_path.to_owned(),
                    actual: u64::MAX,
                    limit: max_source_archive_bytes,
                })?;
        if actual_bytes > max_source_archive_bytes {
            return Err(OpcWriteError::SourceArchiveTooLarge {
                path: source_path.to_owned(),
                actual: actual_bytes,
                limit: max_source_archive_bytes,
            });
        }
        snapshot.write_all(&buffer[..count])?;
        hasher.update(&buffer[..count]);
    }
    let actual_sha256 = hex::encode(hasher.finalize());
    if actual_bytes != expected.byte_size || actual_sha256 != expected.sha256 {
        return Err(OpcWriteError::SourceIdentityMismatch {
            path: source_path.to_owned(),
            expected_bytes: expected.byte_size,
            actual_bytes,
            expected_sha256: expected.sha256.clone(),
            actual_sha256,
        });
    }
    snapshot.as_file_mut().flush()?;
    snapshot.as_file().sync_all()?;
    Ok(snapshot)
}

fn ensure_destination_is_not_source(
    destination: &Path,
    source: &SourceIdentity,
) -> Result<(), OpcWriteError> {
    if destination == source.canonical_path {
        return Err(OpcWriteError::SourceDestinationCollision {
            destination: destination.to_owned(),
            source_archive: source.canonical_path.clone(),
        });
    }
    if let Ok(metadata) = fs::metadata(destination) {
        let same_canonical_path = fs::canonicalize(destination)
            .map(|path| path == source.canonical_path)
            .unwrap_or(false);
        if same_canonical_path || source.matches_metadata(&metadata) {
            return Err(OpcWriteError::SourceDestinationCollision {
                destination: destination.to_owned(),
                source_archive: source.canonical_path.clone(),
            });
        }
    }
    Ok(())
}

fn verify_open_source_identity(
    file: &mut File,
    path: &Path,
    expected: &ExpectedSourceIdentity,
) -> Result<(), OpcWriteError> {
    let metadata_size = file.metadata()?.len();
    let (actual_size, actual_sha256) = hash_open_file(file)?;
    if metadata_size != actual_size
        || actual_size != expected.byte_size
        || actual_sha256 != expected.sha256
    {
        return Err(OpcWriteError::SourceIdentityMismatch {
            path: path.to_owned(),
            expected_bytes: expected.byte_size,
            actual_bytes: actual_size,
            expected_sha256: expected.sha256.clone(),
            actual_sha256,
        });
    }
    Ok(())
}

fn ensure_source_path_identity(
    identity: &SourceIdentity,
    expected: &ExpectedSourceIdentity,
) -> Result<(), OpcWriteError> {
    let canonical_now = fs::canonicalize(&identity.canonical_path)
        .map_err(|_| OpcWriteError::SourcePathIdentityChanged(identity.canonical_path.clone()))?;
    if canonical_now != identity.canonical_path {
        return Err(OpcWriteError::SourcePathIdentityChanged(
            identity.canonical_path.clone(),
        ));
    }
    let metadata = fs::metadata(&canonical_now)
        .map_err(|_| OpcWriteError::SourcePathIdentityChanged(identity.canonical_path.clone()))?;

    #[cfg(unix)]
    if !identity.matches_metadata(&metadata) {
        return Err(OpcWriteError::SourcePathIdentityChanged(
            identity.canonical_path.clone(),
        ));
    }

    #[cfg(not(unix))]
    {
        let mut current = File::open(&canonical_now).map_err(|_| {
            OpcWriteError::SourcePathIdentityChanged(identity.canonical_path.clone())
        })?;
        verify_open_source_identity(&mut current, &canonical_now, expected)?;
    }
    #[cfg(unix)]
    let _ = expected;
    Ok(())
}

fn ensure_open_file_matches_path(file: &File, path: &Path) -> Result<(), OpcWriteError> {
    let open_metadata = file.metadata()?;
    let path_metadata = fs::metadata(path)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        if open_metadata.dev() != path_metadata.dev() || open_metadata.ino() != path_metadata.ino()
        {
            return Err(OpcWriteError::StagedPackagePathIdentityChanged);
        }
    }
    #[cfg(not(unix))]
    let _ = (open_metadata, path_metadata);
    Ok(())
}

fn compression_ratio(uncompressed: u64, compressed: u64) -> f64 {
    match (uncompressed, compressed) {
        (0, _) => 1.0,
        (_, 0) => f64::INFINITY,
        (size, compressed_size) => size as f64 / compressed_size as f64,
    }
}

fn entry_size_limit(path: &str, limits: &OpcWriteLimits) -> u64 {
    let lowercase = path.to_ascii_lowercase();
    if lowercase.starts_with("3d/") && lowercase.ends_with(".model") {
        limits.max_model_entry_uncompressed_bytes
    } else if lowercase.ends_with(".config") {
        limits.max_config_entry_uncompressed_bytes
    } else if lowercase.ends_with(".rels") || lowercase == "[content_types].xml" {
        limits.max_relationship_entry_uncompressed_bytes
    } else {
        limits.max_entry_uncompressed_bytes
    }
}

fn deterministic_options(fixed_time: DateTime, size: u64) -> SimpleFileOptions {
    SimpleFileOptions::default()
        .compression_method(CompressionMethod::Deflated)
        .compression_level(Some(DETERMINISTIC_DEFLATE_LEVEL))
        .last_modified_time(fixed_time)
        .unix_permissions(DETERMINISTIC_FILE_MODE)
        .large_file(size > u32::MAX as u64)
}

fn is_symbolic_link(unix_mode: Option<u32>) -> bool {
    unix_mode.is_some_and(|mode| mode & 0o170000 == 0o120000)
}

fn copy_exact(
    reader: &mut impl Read,
    writer: &mut impl Write,
    expected: u64,
    buffer: &mut [u8],
    output_path: &str,
) -> Result<(), OpcWriteError> {
    let mut copied = 0_u64;
    while copied < expected {
        let remaining = expected - copied;
        let requested = usize::try_from(remaining.min(buffer.len() as u64))
            .expect("bounded buffer length fits usize");
        let count = reader.read(&mut buffer[..requested])?;
        if count == 0 {
            return Err(OpcWriteError::CopiedEntrySizeMismatch {
                path: output_path.to_owned(),
                actual: copied,
                expected,
            });
        }
        writer.write_all(&buffer[..count])?;
        copied += count as u64;
    }

    let mut probe = [0_u8; 1];
    if reader.read(&mut probe)? != 0 {
        return Err(OpcWriteError::CopiedEntrySizeMismatch {
            path: output_path.to_owned(),
            actual: copied.saturating_add(1),
            expected,
        });
    }
    Ok(())
}

#[cfg(test)]
fn hash_file(path: &Path) -> Result<(u64, String), OpcWriteError> {
    let mut file = File::open(path)?;
    hash_open_file(&mut file)
}

fn hash_open_file(file: &mut File) -> Result<(u64, String), OpcWriteError> {
    file.seek(SeekFrom::Start(0))?;
    let mut buffer = [0_u8; 128 * 1024];
    let mut bytes = 0_u64;
    let mut hasher = Sha256::new();
    loop {
        let count = file.read(&mut buffer)?;
        if count == 0 {
            break;
        }
        hasher.update(&buffer[..count]);
        bytes = bytes
            .checked_add(count as u64)
            .ok_or(OpcWriteError::PackageTooLarge {
                actual: u64::MAX,
                limit: u64::MAX,
            })?;
    }
    file.seek(SeekFrom::Start(0))?;
    Ok((bytes, hex::encode(hasher.finalize())))
}

fn hash_open_file_at_most(
    file: &mut File,
    byte_limit: u64,
) -> Result<(u64, String), OpcWriteError> {
    file.seek(SeekFrom::Start(0))?;
    let mut buffer = [0_u8; 128 * 1024];
    let mut bytes = 0_u64;
    let mut hasher = Sha256::new();
    while bytes < byte_limit {
        let remaining = byte_limit - bytes;
        let requested = usize::try_from(remaining.min(buffer.len() as u64))
            .expect("bounded buffer length fits usize");
        let count = file.read(&mut buffer[..requested])?;
        if count == 0 {
            break;
        }
        hasher.update(&buffer[..count]);
        bytes += count as u64;
    }
    file.seek(SeekFrom::Start(0))?;
    Ok((bytes, hex::encode(hasher.finalize())))
}

fn map_persist_error(destination: &Path, error: PersistError) -> OpcWriteError {
    if error.error.kind() == io::ErrorKind::AlreadyExists
        || matches!(destination.try_exists(), Ok(true))
    {
        OpcWriteError::OutputExists(destination.to_owned())
    } else {
        OpcWriteError::Publish {
            path: destination.to_owned(),
            source: error.error,
        }
    }
}

#[cfg(unix)]
fn sync_parent_directory(destination: &Path) -> Result<(), OpcWriteError> {
    let parent = destination.parent().ok_or_else(|| {
        OpcWriteError::InvalidDestination("destination has no parent directory".into())
    })?;
    File::open(parent)
        .and_then(|directory| directory.sync_all())
        .map_err(|source| OpcWriteError::DirectorySync {
            path: destination.to_owned(),
            source,
        })
}

#[cfg(not(unix))]
fn sync_parent_directory(_destination: &Path) -> Result<(), OpcWriteError> {
    // Windows does not provide a portable directory fsync through std. The file
    // itself was synchronized before the atomic persistence operation.
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Cursor, Seek};
    use tempfile::tempdir;

    fn source_zip(path: &Path, entries: &[(&str, &[u8])]) {
        let file = File::create(path).unwrap();
        let mut writer = ZipWriter::new(file);
        for (name, data) in entries {
            writer
                .start_file(*name, SimpleFileOptions::default())
                .unwrap();
            writer.write_all(data).unwrap();
        }
        writer.finish().unwrap().sync_all().unwrap();
    }

    fn compressed_payload(path: &Path, entry_name: &str) -> Vec<u8> {
        let file = File::open(path).unwrap();
        let mut archive = ZipArchive::new(file).unwrap();
        let (data_start, compressed_size) = {
            let entry = archive.by_name(entry_name).unwrap();
            (entry.data_start(), entry.compressed_size())
        };
        let mut file = archive.into_inner();
        file.seek(io::SeekFrom::Start(data_start)).unwrap();
        let mut bytes = vec![0_u8; usize::try_from(compressed_size).unwrap()];
        file.read_exact(&mut bytes).unwrap();
        bytes
    }

    fn expected_source_identity(path: &Path) -> ExpectedSourceIdentity {
        let (byte_size, sha256) = hash_file(path).unwrap();
        ExpectedSourceIdentity::new(byte_size, sha256).unwrap()
    }

    fn validated_test_package(
        destination: PathBuf,
        contents: &[u8],
    ) -> (ValidatedStagedPackage, PathBuf) {
        let private_directory = private_staging_directory(destination.parent().unwrap()).unwrap();
        let mut temporary = NamedTempFile::new_in(private_directory.path()).unwrap();
        temporary.write_all(contents).unwrap();
        temporary.as_file_mut().flush().unwrap();
        temporary.as_file().sync_all().unwrap();
        let private_path = temporary.path().to_owned();
        let (package_bytes, package_sha256) = hash_open_file(temporary.as_file_mut()).unwrap();
        let report = OpcWriteReport {
            destination: destination.clone(),
            package_bytes,
            package_sha256,
            total_uncompressed_bytes: 0,
            entries: Vec::new(),
            verified_sources: Vec::new(),
        };
        (
            ValidatedStagedPackage {
                private_directory,
                temporary,
                destination,
                source_identities: Vec::new(),
                report,
                validation: OutputValidationReport::default(),
            },
            private_path,
        )
    }

    #[test]
    fn rejects_unsafe_and_duplicate_output_paths() {
        let mut writer = OpcPackageWriter::new();
        assert!(matches!(
            writer.add_bytes("../escape", b"bad"),
            Err(OpcWriteError::UnsafeEntryPath { .. })
        ));
        writer.add_bytes("3D/model.model", b"first").unwrap();
        assert!(matches!(
            writer.add_bytes("3D/model.model", b"second"),
            Err(OpcWriteError::DuplicateOutputEntry(path)) if path == "3D/model.model"
        ));
        assert!(matches!(
            writer.add_bytes("3d/MODEL.MODEL", b"alias"),
            Err(OpcWriteError::EquivalentOutputEntry { .. })
        ));

        let mut prefix_writer = OpcPackageWriter::new();
        prefix_writer.add_bytes("Metadata", b"part").unwrap();
        assert!(matches!(
            prefix_writer.add_bytes("Metadata/settings.config", b"derived"),
            Err(OpcWriteError::OutputPartNameDerivationConflict { .. })
        ));
    }

    #[test]
    fn stages_deterministically_and_streams_selected_source_entries() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(
            &source,
            &[("3D/source.model", b"source geometry"), ("ignored", b"x")],
        );

        let mut writer = OpcPackageWriter::new();
        // Add in reverse lexical order to prove that archive ordering is stable.
        writer.add_bytes("z.config", b"generated metadata").unwrap();
        writer
            .copy_zip_entry(
                "3D/copied.model",
                &source,
                expected_source_identity(&source),
                "3D/source.model",
            )
            .unwrap();
        writer
            .add_bytes("[Content_Types].xml", b"content types")
            .unwrap();

        let first = writer.stage_to(directory.path().join("first.3mf")).unwrap();
        let second = writer
            .stage_to(directory.path().join("second.3mf"))
            .unwrap();
        assert_eq!(
            first.report().package_sha256,
            second.report().package_sha256
        );
        assert_eq!(first.report().package_bytes, second.report().package_bytes);
        assert!(!first.destination().exists());

        let expected_names = vec![
            "3D/copied.model".to_owned(),
            "[Content_Types].xml".to_owned(),
            "z.config".to_owned(),
        ];
        assert_eq!(
            first
                .report()
                .entries
                .iter()
                .map(|entry| entry.path.clone())
                .collect::<Vec<_>>(),
            expected_names
        );

        let bytes = fs::read(first.path()).unwrap();
        let mut archive = ZipArchive::new(Cursor::new(bytes)).unwrap();
        assert_eq!(archive.len(), 3);
        for (index, expected_name) in expected_names.iter().enumerate() {
            let mut entry = archive.by_index(index).unwrap();
            assert_eq!(entry.name(), expected_name);
            assert_eq!(entry.compression(), CompressionMethod::Deflated);
            let modified = entry.last_modified().expect("fixed ZIP timestamp");
            assert_eq!(modified.year(), 1980);
            assert_eq!(modified.month(), 1);
            assert_eq!(modified.day(), 1);
            if expected_name == "3D/copied.model" {
                let mut copied = String::new();
                entry.read_to_string(&mut copied).unwrap();
                assert_eq!(copied, "source geometry");
            }
        }
    }

    #[test]
    fn publication_never_overwrites_an_existing_file() {
        let directory = tempdir().unwrap();
        let destination = directory.path().join("output.3mf");
        fs::write(&destination, b"old").unwrap();
        let (validated, _) = validated_test_package(destination.clone(), b"new");
        assert_eq!(fs::read(&destination).unwrap(), b"old");
        let result = validated.publish();
        assert!(
            matches!(
                result, Err(OpcWriteError::OutputExists(ref path)) if path == &destination
            ),
            "unexpected publish result: {result:?}"
        );
        assert_eq!(fs::read(&destination).unwrap(), b"old");
    }

    #[test]
    fn validated_capability_rejects_a_private_staging_path_swap() {
        let directory = tempdir().unwrap();
        let destination = directory.path().join("output.3mf");
        let (validated, private_path) = validated_test_package(destination.clone(), b"validated");
        let displaced_path = private_path.with_extension("displaced");
        fs::rename(&private_path, &displaced_path).unwrap();
        fs::write(&private_path, b"validated").unwrap();

        assert!(matches!(
            validated.publish(),
            Err(OpcWriteError::StagedPackagePathIdentityChanged)
        ));
        assert!(!destination.exists());
    }

    #[test]
    fn trusted_raw_copy_preserves_compressed_geometry_bytes_and_is_deterministic() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        let geometry = b"repeated geometry data repeated geometry data repeated geometry data";
        source_zip(&source, &[("3D/Objects/part.model", geometry)]);
        let source_compressed = compressed_payload(&source, "3D/Objects/part.model");

        let mut writer = OpcPackageWriter::new();
        writer
            .copy_zip_entry_raw(
                &source,
                expected_source_identity(&source),
                "3D/Objects/part.model",
            )
            .unwrap();
        let first = writer.stage_to(directory.path().join("first.3mf")).unwrap();
        let second = writer
            .stage_to(directory.path().join("second.3mf"))
            .unwrap();

        assert_eq!(
            compressed_payload(first.path(), "3D/Objects/part.model"),
            source_compressed
        );
        assert_eq!(
            first.report().package_sha256,
            second.report().package_sha256
        );
        assert!(matches!(
            &first.report().entries[0].origin,
            OpcEntryOrigin::Copied { raw: true, .. }
        ));
    }

    #[test]
    fn refuses_to_stage_over_a_source_archive() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(&source, &[("entry", b"content")]);

        let mut writer = OpcPackageWriter::new();
        writer
            .copy_zip_entry("copy", &source, expected_source_identity(&source), "entry")
            .unwrap();
        assert!(matches!(
            writer.stage_to(&source),
            Err(OpcWriteError::SourceDestinationCollision { .. })
        ));
    }

    #[test]
    fn refuses_a_source_archive_that_changed_after_analysis() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(&source, &[("entry", b"analyzed content")]);
        let expected = expected_source_identity(&source);
        source_zip(&source, &[("entry", b"modified content")]);

        let mut writer = OpcPackageWriter::new();
        writer
            .copy_zip_entry("copy", &source, expected, "entry")
            .unwrap();
        let result = writer.stage_to(directory.path().join("output.3mf"));
        assert!(
            matches!(result, Err(OpcWriteError::SourceIdentityMismatch { .. })),
            "unexpected stage result: {result:?}"
        );
    }

    #[test]
    fn verifies_a_registered_source_even_when_no_entries_are_copied() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(&source, &[("entry", b"analyzed content")]);
        let expected = expected_source_identity(&source);

        let mut writer = OpcPackageWriter::new();
        writer
            .verify_zip_source(&source, expected.clone())
            .unwrap()
            .add_bytes("rewritten", b"generated content")
            .unwrap();
        let staged = writer
            .stage_to(directory.path().join("output.3mf"))
            .unwrap();

        assert_eq!(
            staged.report().verified_sources,
            vec![VerifiedSourceIdentity {
                byte_size: expected.byte_size(),
                sha256: expected.sha256().to_owned(),
            }]
        );
    }

    #[test]
    fn registered_source_change_is_detected_when_no_entries_are_copied() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(&source, &[("entry", b"analyzed content")]);
        let expected = expected_source_identity(&source);

        let mut writer = OpcPackageWriter::new();
        writer
            .verify_zip_source(&source, expected)
            .unwrap()
            .add_bytes("rewritten", b"generated content")
            .unwrap();
        source_zip(&source, &[("entry", b"modified content")]);

        let result = writer.stage_to(directory.path().join("output.3mf"));
        assert!(
            matches!(result, Err(OpcWriteError::SourceIdentityMismatch { .. })),
            "unexpected stage result: {result:?}"
        );
    }

    #[test]
    fn final_original_source_handle_rehash_detects_an_in_place_rewrite() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(&source, &[("entry", b"analyzed content")]);
        let expected = expected_source_identity(&source);
        let mut original_file = File::open(&source).unwrap();
        let original_metadata = original_file.metadata().unwrap();
        let _snapshot = snapshot_source_archive(
            &mut original_file,
            &source,
            &expected,
            OpcWriteLimits::default().max_source_archive_bytes,
            directory.path(),
        )
        .unwrap();
        let mut changed = fs::read(&source).unwrap();
        let changed_index = changed.len() / 2;
        changed[changed_index] ^= 0x01;
        fs::write(&source, changed).unwrap();

        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            let changed_metadata = fs::metadata(&source).unwrap();
            assert_eq!(original_metadata.dev(), changed_metadata.dev());
            assert_eq!(original_metadata.ino(), changed_metadata.ino());
        }
        assert!(matches!(
            verify_open_source_identity(&mut original_file, &source, &expected),
            Err(OpcWriteError::SourceIdentityMismatch { .. })
        ));
    }

    #[test]
    fn rejects_conflicting_expected_identities_for_one_source() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(&source, &[("one", b"one"), ("two", b"two")]);
        let expected = expected_source_identity(&source);
        let conflicting =
            ExpectedSourceIdentity::new(expected.byte_size(), "00".repeat(32)).unwrap();

        let mut writer = OpcPackageWriter::new();
        writer
            .copy_zip_entry("copy-one", &source, expected, "one")
            .unwrap();
        writer
            .copy_zip_entry("copy-two", &source, conflicting, "two")
            .unwrap();
        assert!(matches!(
            writer.stage_to(directory.path().join("output.3mf")),
            Err(OpcWriteError::ConflictingExpectedSourceIdentity { .. })
        ));
    }

    #[test]
    fn rejects_duplicate_entries_in_a_source_archive() {
        let directory = tempdir().unwrap();
        let source = directory.path().join("source.3mf");
        source_zip(&source, &[("same", b"one"), ("sAme", b"two")]);
        // zip 4.6 correctly refuses duplicate names at write time. Craft the
        // malicious fixture by changing the equal-length second name in both
        // its local header and central directory.
        let mut bytes = fs::read(&source).unwrap();
        let mut replacements = 0;
        for offset in 0..=bytes.len() - 4 {
            if &bytes[offset..offset + 4] == b"sAme" {
                bytes[offset..offset + 4].copy_from_slice(b"same");
                replacements += 1;
            }
        }
        assert_eq!(replacements, 2);
        fs::write(&source, bytes).unwrap();

        let mut writer = OpcPackageWriter::new();
        writer
            .copy_zip_entry("copy", &source, expected_source_identity(&source), "same")
            .unwrap();
        let result = writer.stage_to(directory.path().join("output.3mf"));
        assert!(
            matches!(
                result,
                Err(OpcWriteError::DuplicateSourceEntry { ref entry, .. }) if entry == "same"
            ),
            "unexpected stage result: {result:?}"
        );
    }

    #[test]
    fn total_size_limit_fails_without_creating_the_destination() {
        let directory = tempdir().unwrap();
        let destination = directory.path().join("output.3mf");
        let limits = OpcWriteLimits {
            max_entry_uncompressed_bytes: 10,
            max_total_uncompressed_bytes: 5,
            ..OpcWriteLimits::default()
        };
        let mut writer = OpcPackageWriter::with_limits(limits).unwrap();
        writer.add_bytes("one", b"123").unwrap();
        assert!(matches!(
            writer.add_bytes("two", b"456"),
            Err(OpcWriteError::PackageTooLarge {
                actual: 6,
                limit: 5
            })
        ));
        assert!(!destination.exists());
    }

    #[test]
    fn config_limit_is_stricter_than_the_generic_entry_limit() {
        let limits = OpcWriteLimits {
            max_entry_uncompressed_bytes: 1_024,
            max_config_entry_uncompressed_bytes: 4,
            ..OpcWriteLimits::default()
        };
        let mut writer = OpcPackageWriter::with_limits(limits).unwrap();
        assert!(matches!(
            writer.add_bytes("Metadata/PROJECT_SETTINGS.CONFIG", b"12345"),
            Err(OpcWriteError::EntryTooLarge {
                actual: 5,
                limit: 4,
                ..
            })
        ));
        writer.add_bytes("Metadata/data.bin", b"12345").unwrap();
    }

    #[test]
    fn model_and_relationship_limits_are_type_aware_case_insensitively() {
        let limits = OpcWriteLimits {
            max_entry_uncompressed_bytes: 4,
            max_model_entry_uncompressed_bytes: 8,
            max_relationship_entry_uncompressed_bytes: 3,
            ..OpcWriteLimits::default()
        };
        let mut writer = OpcPackageWriter::with_limits(limits).unwrap();
        writer.add_bytes("3D/PART.MODEL", b"123456").unwrap();
        assert!(matches!(
            writer.add_bytes("3D/_RELS/PART.MODEL.RELS", b"1234"),
            Err(OpcWriteError::EntryTooLarge {
                actual: 4,
                limit: 3,
                ..
            })
        ));
        assert!(matches!(
            writer.add_bytes("Metadata/data.bin", b"12345"),
            Err(OpcWriteError::EntryTooLarge {
                actual: 5,
                limit: 4,
                ..
            })
        ));
    }

    #[test]
    fn staged_file_is_a_complete_seekable_zip() {
        let directory = tempdir().unwrap();
        let mut writer = OpcPackageWriter::new();
        writer.add_bytes("entry", b"content").unwrap();
        let staged = writer
            .stage_to(directory.path().join("output.3mf"))
            .unwrap();

        let mut file = File::open(staged.path()).unwrap();
        file.seek(io::SeekFrom::End(0)).unwrap();
        assert!(file.stream_position().unwrap() > 0);
        file.rewind().unwrap();
        assert_eq!(ZipArchive::new(file).unwrap().len(), 1);
    }
}
